name = "SparseBandedMatrices"
uuid = "bd59d7e1-4699-4102-944e-d05209cb92aa"
authors = ["Shreyas Ekanathan, Oscar Smith"]
version = "1.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Aqua = "0.8"
JET = "0.9, 0.10, 0.11"
LinearAlgebra = "1"
PrecompileTools = "1"
Random = "1"
SafeTestsets = "0.1"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Random", "SafeTestsets", "Test"]
