name = "SparseBandedMatrices"
uuid = "bd59d7e1-4699-4102-944e-d05209cb92aa"
authors = ["Shreyas Ekanathan, Oscar Smith"]
version = "1.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1"
julia = "1.10"
