name = "SparseBandedMatrices"
uuid = "bd59d7e1-4699-4102-944e-d05209cb92aa"
authors = ["Shreyas Ekanathan, Oscar Smith"]
version = "1.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
LinearAlgebra = "1"
PrecompileTools = "1"
julia = "1.10"
